model:
  name: "Qwen/Qwen3-4B-Thinking-2507"
  max_tokens: 16384
  trust_remote_code: true
  gpu_memory_utilization: 0.9

parallel:
  dp_size: 2
  tp_size: 1
  node_size: 1
  node_rank: 0

data:
  dataset_path: "./data/train/deepscaler.json"
  num_samples: 2  # 0 for all
  K: 8

sampling:
  temperature: 0.7
  top_p: 0.95
  seed_offset: 42

prompt:
  nothinking: false
  think: "<|im_start|>user\n{question}<|im_end|>\n<|im_start|>assistant\n<think>"
  nothink: "<|im_start|>user\n{question}<|im_end|>\n<|im_start|>assistant\n<think>\n</think>"

output:
  output_dir: "./data/train"
  save_intermediate: false  # Keep or delete rank files
